// appData.js — Static option lists for all dropdowns.
// Import this on any page with: <script src="appData.js"></script>
// Then access via APP_OPTIONS.<field>

const APP_OPTIONS = {

  // ── Reactions ─────────────────────────────────────────────────────────────
  // Names match the Reaction column in lser.csv exactly.
  reactions: [
    'Allylation',
    'Amidation',
    'Aza-Michael (bimolecular)',
    'Aza-Michael (trimolecular)',
    'Diazo esterification/O-alkylation',
    'Esterification',
    'Esterification (enzymatic)',
    'Fluorination',
    'Hydrogenation (nitrobenzene to aniline)',
    'Mannich reaction',
    'Menschutkin reaction',
    'Michael addition reaction',
    'Mizoroki\u2013Heck reaction',
    'N-arylation',
    'Ring closing metathesis',
    'SN1',
    'SN2',
    'Transesterification',
    'Other',
  ],

  // ── Reaction data for autocomplete ────────────────────────────────────────
  // Keyed by reaction name. Populates reactant name fields and orders when
  // the user picks a reaction. null = reactant not used for this reaction.
  reactionData: {
    'Allylation': {
      temp: 30,
      A: { name: 'Allyl bromide',          formula: 'C3H5Br',      order: 1, rmm: 121.0 },
      B: { name: 'Morpholine',             formula: 'C4H9NO',      order: 1, rmm:  87.1 },
      C: null,
      productName: 'N-Allylmorpholine',    productFormula: 'C7H13NO',   productRmm: 127.2,
    },
    'Amidation': {
      temp: 100,
      A: { name: 'Benzylamine',            formula: 'C7H9N',       order: 1, rmm: 107.2 },
      B: { name: '4-Phenylbutyric acid',   formula: 'C10H12O2',    order: 1, rmm: 164.2 },
      C: null,
      productName: 'N-Benzyl-4-phenylbutanamide', productFormula: 'C17H19NO',  productRmm: 253.3,
    },
    'Aza-Michael (bimolecular)': {
      temp: 30,
      A: { name: 'Dimethyl itaconate',     formula: 'C7H10O4',     order: 1, rmm: 158.2 },
      B: { name: 'Piperidine',             formula: 'C5H11N',      order: 1, rmm:  85.1 },
      C: null,
      productName: 'Dimethyl 2-(piperidin-1-ylmethyl)succinate', productFormula: 'C12H21NO4', productRmm: 243.3,
    },
    'Aza-Michael (trimolecular)': {
      temp: 30,
      A: { name: 'Dimethyl itaconate',     formula: 'C7H10O4',     order: 1, rmm: 158.2 },
      B: { name: 'Piperidine',             formula: 'C5H11N',      order: 2, rmm:  85.1 },
      C: null,
      productName: 'Dimethyl 2-(piperidin-1-ylmethyl)succinate', productFormula: 'C12H21NO4', productRmm: 243.3,
    },
    'Diazo esterification/O-alkylation': {
      temp: 30,
      A: { name: 'Diazodiphenylmethane',       formula: 'C13H10N2',  order: 1, rmm: 194.2 },
      B: { name: 'Cyclohex-1-eneacetic acid',  formula: 'C8H12O2',   order: 1, rmm: 140.2 },
      C: null,
      productName: 'Diphenylmethyl cyclohex-1-ene-1-acetate', productFormula: 'C21H22O2', productRmm: 306.4,
    },
    'Esterification': {
      temp: 50,
      A: { name: 'Benzyl alcohol',         formula: 'C7H8O',       order: 1, rmm: 108.1 },
      B: { name: 'Acetic acid',            formula: 'C2H4O2',      order: 1, rmm:  60.1 },
      C: null,
      productName: 'Benzyl acetate',       productFormula: 'C9H10O2',   productRmm: 150.2,
    },
    'Esterification (enzymatic)': {
      temp: 40,
      A: { name: 'Lauric acid',            formula: 'C12H24O2',    order: 1, rmm: 200.3 },
      B: { name: '1-Hexanol',             formula: 'C6H14O',      order: 1, rmm: 102.2 },
      C: null,
      productName: 'Hexyl laurate',        productFormula: 'C18H36O2',  productRmm: 284.5,
    },
    'Fluorination': {
      temp: 90,
      A: { name: '2-Chloro-5-nitropyridine', formula: 'C5H3ClN2O2', order: 1, rmm: 158.5 },
      B: { name: 'Potassium fluoride',       formula: 'KF',          order: 1, rmm:  58.1 },
      C: null,
      productName: '2-Fluoro-5-nitropyridine', productFormula: 'C5H3FN2O2', productRmm: 142.1,
    },
    'Hydrogenation (nitrobenzene to aniline)': {
      temp: 25,
      A: { name: 'Nitrobenzene',           formula: 'C6H5NO2',     order: 1, rmm: 123.1 },
      B: { name: 'Hydrogen',              formula: 'H2',          order: 0, rmm:   2.0 },
      C: null,
      productName: 'Aniline',             productFormula: 'C6H7N',     productRmm:  93.1,
    },
    'Mannich reaction': {
      temp: 30,
      A: { name: 'Butyraldehyde',          formula: 'C4H8O',       order: 1, rmm:  72.1 },
      B: { name: 'Formaldehyde',           formula: 'CH2O',        order: 1, rmm:  30.0 },
      C: { name: 'Diethylamine',           formula: 'C4H11N',      order: 1, rmm:  73.1 },
      productName: '2-(Diethylaminomethyl)butanal', productFormula: 'C9H19NO', productRmm: 157.3,
    },
    'Menschutkin reaction': {
      temp: 50,
      A: { name: '1,2-Dimethylimidazole',  formula: 'C5H8N2',      order: 1, rmm:  96.1 },
      B: { name: '1-Bromodecane',          formula: 'C10H21Br',    order: 1, rmm: 221.2 },
      C: null,
      productName: '1-Decyl-2,3-dimethylimidazolium bromide', productFormula: 'C15H29BrN2', productRmm: 317.3,
    },
    'Michael addition reaction':{
      temp: 21,
      A: { name: 'Dimethyl malonate',     formula: 'C5H8O4',       order: 1, rmm: 132.11 },
      B: { name: 'Trans-chalcone',        formula: 'C15H12O',      order: 1, rmm:  208.26 },
      C: null,
      productName: 'Dimethyl 2-(3-oxo-1,3-diphenylpropyl)malonate', productFormula: 'C20H20O5',  productRmm: 340.37,
    },
    'Mizoroki\u2013Heck reaction': {
      temp: 100,
      A: { name: 'Iodobenzene',            formula: 'C6H5I',       order: 1, rmm: 204.0 },
      B: { name: 'Methyl acrylate',        formula: 'C4H6O2',      order: 1, rmm:  86.1 },
      C: null,
      productName: 'Methyl (E)-cinnamate', productFormula: 'C10H10O2',  productRmm: 162.2,
    },
    'N-arylation': {
      temp: 25,
      A: { name: '2,4-Dinitrochlorobenzene', formula: 'C6H3ClN2O4', order: 1, rmm: 202.6 },
      B: { name: 'Piperidine',               formula: 'C5H11N',     order: 1, rmm:  85.1 },
      C: null,
      productName: '1-(2,4-Dinitrophenyl)piperidine', productFormula: 'C11H13N3O4', productRmm: 251.2,
    },
    'Ring closing metathesis': {
      temp: 25,
      A: { name: 'Diethyl diallylmalonate', formula: 'C13H20O4',   order: 1, rmm: 240.3 },
      B: null,
      C: null,
      productName: 'Diethyl cyclopent-3-ene-1,1-dicarboxylate', productFormula: 'C11H16O4', productRmm: 212.2,
    },
    'SN1': {
      temp: 25,
      A: { name: 't-Butyl bromide',        formula: 'C4H9Br',      order: 1, rmm: 137.0 },
      B: null,
      C: null,
      productName: 'tert-Butanol',         productFormula: 'C4H10O',    productRmm:  74.1,
    },
    'SN2': {
      temp: 25,
      A: { name: '2-Mercaptobenzoxazole',  formula: 'C7H5NOS',     order: 1, rmm: 151.2 },
      B: { name: 'p-Nitrobenzyl bromide',  formula: 'C7H6BrNO2',   order: 1, rmm: 216.0 },
      C: null,
      productName: '2-(4-Nitrobenzylthio)benzoxazole', productFormula: 'C14H10N2O3S', productRmm: 286.3,
    },
    'Transesterification': {
      temp: 50,
      A: { name: '1-Butanol',             formula: 'C4H10O',      order: 1, rmm:  74.1 },
      B: { name: 'Butyric anhydride',     formula: 'C8H14O3',     order: 1, rmm: 158.2 },
      C: null,
      productName: 'Butyl butyrate',      productFormula: 'C8H16O2',   productRmm: 144.2,
    },
  },

  // ── Process type (REACH PROCs) ────────────────────────────────────────────
  processTypes: [
    { id: 'PROC1',  label: 'PROC1 \u2013 Closed industrial process, no likelihood of exposure' },
    { id: 'PROC2',  label: 'PROC2 \u2013 Closed, continuous process with occasional controlled exposure' },
    { id: 'PROC3',  label: 'PROC3 \u2013 Synthesis or formulation (closed batch process)' },
    { id: 'PROC4',  label: 'PROC4 \u2013 Synthesis (batch and other process where opportunity for exposure arises)' },
    { id: 'PROC5',  label: 'PROC5 \u2013 Mixing or blending in batch processes (multistage and/or significant contact)' },
    { id: 'PROC6',  label: 'PROC6 \u2013 Calendering operations' },
    { id: 'PROC7',  label: 'PROC7 \u2013 Industrial spraying' },
    { id: 'PROC8a', label: 'PROC8a \u2013 Transfer of chemicals from/to vessels at non-dedicated facilities' },
    { id: 'PROC8b', label: 'PROC8b \u2013 Transfer of chemicals from/to vessels at dedicated facilities' },
    { id: 'PROC9',  label: 'PROC9 \u2013 Transfer of chemicals into small containers (dedicated filling line)' },
    { id: 'PROC10', label: 'PROC10 \u2013 Roller application or brushing' },
    { id: 'PROC12', label: 'PROC12 \u2013 Use of blow agents for foam production' },
    { id: 'PROC13', label: 'PROC13 \u2013 Treatment of articles by dipping and pouring' },
    { id: 'PROC14', label: 'PROC14 \u2013 Production of preparations or articles by tabletting, compression, extrusion, pelletisation' },
    { id: 'PROC15', label: 'PROC15 \u2013 R&D (use of laboratory reagents in small scale laboratories)' },
    { id: 'PROC16', label: 'PROC16 \u2013 Using material as fuel sources, limited exposure to unburned product' },
    { id: 'PROC17', label: 'PROC17 \u2013 Lubrication at high energy conditions and in partly open process' },
    { id: 'PROC18', label: 'PROC18 \u2013 Greasing at high energy conditions' },
    { id: 'PROC19', label: 'PROC19 \u2013 Hand-mixing with intimate contact' },
  ],

  // ── Risk scenario ─────────────────────────────────────────────────────────
  exposureTemp: ['Ambient temperature', 'Process temperature'],
  exposureTime: ['<15min', '15min-1hr', '1-4hr', '>4hr'],
  ventilation:  ['No ventilation', 'Basic ventilation', 'Good ventilation', 'Enhanced ventilation'],
  rpe: ['no RPE', '90% effectiveness', '95% effectiveness'],
  ppe: ['no PPE', '80% effectiveness', '90% effectiveness', '95% effectiveness'],

  // ── End-of-life & impact ──────────────────────────────────────────────────
  endOfLife: [
    'Incinerated',
    'Recycled by distillation',
    'Released to environment',
    'Retained in product',
  ],

  // Grid electricity carbon intensity by country/region (IEA data).
  // Breaking a long list across lines — just end each entry with a comma
  // and start a new line; JS ignores whitespace inside array literals.
  energyIntensity: [
    'Afghanistan',            'Africa',                 'Albania',
    'Algeria',                'American Samoa',         'Angola',
    'Antigua and Barbuda',    'Argentina',              'Armenia',
    'Aruba',                  'Asia',                   'Australia',
    'Austria',                'Azerbaijan',             'Bahamas (the)',
    'Bahrain',                'Bangladesh',             'Barbados',
    'Belarus',                'Belgium',                'Belize',
    'Benin',                  'Bermuda',                'Bhutan',
    'Bolivia',                'Bosnia Herzegovina',     'Botswana',
    'Brazil',                 'Brunei Darussalam',      'Bulgaria',
    'Burkina Faso',           'Burundi',                'Cabo Verde',
    'Cambodia',               'Cameroon',               'Canada',
    'Cayman Islands (the)',   'Chad',                   'Chile',
    'China',                  'Colombia',               'Comoros (the)',
    'Congo (the Democratic Republic of the)',           'Congo (the)',
    'Cook Islands (the)',     'Costa Rica',             "Cote d'Ivoire",
    'Croatia',                'Cuba',                   'Cyprus',
    'Czechia',                'Denmark',                'Djibouti',
    'Dominica',               'Dominican Republic (the)',
    'Ecuador',                'Egypt',                  'El Salvador',
    'Equatorial Guinea',      'Eritrea',                'Estonia',
    'Eswatini',               'Ethiopia',               'EU',
    'Europe',                 'Falkland Islands (the) [Malvinas]',
    'Faroe Islands (the)',    'Fiji',                   'Finland',
    'France',                 'French Guiana',          'French Polynesia',
    'Gabon',                  'Gambia (the)',            'Georgia',
    'Germany',                'Ghana',                  'Gibraltar',
    'Greece',                 'Greenland',              'Grenada',
    'Guadeloupe',             'Guam',                   'Guatemala',
    'Guinea',                 'Guinea-Bissau',           'Guyana',
    'Haiti',                  'Honduras',               'Hong Kong',
    'Hungary',                'Iceland',                'India',
    'Indonesia',              'Iran (Islamic Republic of)',
    'Iraq',                   'Ireland',                'Israel',
    'Italy',                  'Jamaica',                'Japan',
    'Jordan',                 'Kazakhstan',             'Kenya',
    'Kiribati',               "Korea (the Democratic People's Republic of)",
    'Kosovo',                 'Kuwait',                 'Kyrgyzstan',
    "Lao People's Democratic Republic (the)",
    'Latin America and Caribbean',
    'Latvia',                 'Lebanon',                'Lesotho',
    'Liberia',                'Libya',                  'Lithuania',
    'Luxembourg',             'Macao',                  'Madagascar',
    'Malawi',                 'Malaysia',               'Maldives',
    'Mali',                   'Malta',                  'Martinique',
    'Mauritania',             'Mauritius',              'Mexico',
    'Moldova',                'Mongolia',               'Montenegro',
    'Montserrat',             'Morocco',                'Mozambique',
    'Myanmar',                'Namibia',                'Nauru',
    'Nepal',                  'Netherlands',            'New Caledonia',
    'New Zealand',            'Niger (the)',            'Nigeria',
    'North America',          'North Macedonia',        'Norway',
    'Oceania',                'Oman',                   'Pakistan',
    'Palestine, State of',    'Panama',                 'Papua New Guinea',
    'Paraguay',               'Peru',                   'Philippines (the)',
    'Poland',                 'Portugal',               'Puerto Rico',
    'Qatar',                  'Reunion',                'Romania',
    'Russian Federation (the)',
    'Rwanda',                 'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',  'Saint Lucia',            'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',                  'Sao Tome and Principe',  'Saudi Arabia',
    'Senegal',                'Serbia',                 'Seychelles',
    'Sierra Leone',           'Singapore',              'Slovakia',
    'Slovenia',               'Solomon Islands',        'Somalia',
    'South Africa',           'South Korea',            'South Sudan',
    'Spain',                  'Sri Lanka',              'Sudan (the)',
    'Suriname',               'Sweden',                 'Switzerland',
    'Syrian Arab Republic (the)',
    'Taiwan',                 'Tajikistan',             'Tanzania, the United Republic of',
    'Thailand',               'Timor-Leste',            'Togo',
    'Tonga',                  'Trinidad and Tobago',    'Tunisia',
    'Turkey',                 'Turkmenistan',           'Turks and Caicos Islands (the)',
    'Uganda',                 'Ukraine',                'United Arab Emirates',
    'United Kingdom',         'United States of America',
    'Uruguay',                'Uzbekistan',             'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',               'Virgin Islands (British)',
    'Virgin Islands (U.S.)',  'World',                  'Yemen',
    'Zambia',                 'Zimbabwe',
  ],

  // ── Grid electricity CO₂ intensity by region (IEA data, gCO₂-eq/kWh) ─────
  // Source: national_economics.csv — latest available year per region.
  // Source: Ember yearly electricity data (via Process model sheet).
  // "EU-27" mirrors "EU"; "Global" mirrors "World".
  co2Intensity: {
    "Afghanistan": 123.71, "Africa": 544.85, "Albania": 24.42,
    "Algeria": 633.65, "American Samoa": 647.06, "Angola": 167.22,
    "Antigua and Barbuda": 611.11, "Argentina": 344.83, "Armenia": 242.97,
    "Aruba": 550.0, "Asia": 569.87, "Australia": 553.83,
    "Austria": 113.91, "Azerbaijan": 632.76, "Bahamas (the)": 653.66,
    "Bahrain": 902.41, "Bangladesh": 691.99, "Barbados": 600.0,
    "Belarus": 289.02, "Belgium": 149.77, "Belize": 155.56,
    "Benin": 590.0, "Bermuda": 640.63, "Bhutan": 24.19,
    "Bolivia": 468.02, "Bosnia Herzegovina": 611.71, "Botswana": 849.42,
    "Brazil": 106.06, "Brunei Darussalam": 714.29, "Bulgaria": 313.9,
    "Cambodia": 504.94, "Cameroon": 224.44, "Canada": 173.93,
    "Cayman Islands": 613.95, "Central America": 277.4, "Chile": 321.71,
    "China": 584.39, "Colombia": 216.49, "Congo": 34.67,
    "Costa Rica": 28.25, "Croatia": 155.61, "Cuba": 745.49,
    "Cyprus": 534.07, "Czechia": 411.43, "Democratic Republic of Congo": 24.77,
    "Denmark": 148.11, "Dominican Republic": 601.36, "Ecuador": 180.11,
    "Egypt": 486.28, "El Salvador": 301.71, "Eritrea": 672.35,
    "Estonia": 308.29, "Ethiopia": 21.07, "EU": 210.29,
    "EU-27": 210.29, "Europe": 264.41, "Fiji": 474.05,
    "Finland": 90.7, "France": 56.31, "Gabon": 378.88,
    "Georgia": 131.99, "Germany": 380.72, "Ghana": 389.4,
    "Global": 471.59, "Greece": 298.3, "Guatemala": 362.07,
    "Guinea": 341.96, "Guyana": 636.07, "Haiti": 600.0,
    "Honduras": 316.47, "Hong Kong": 586.19, "Hungary": 181.58,
    "Iceland": 0.0, "India": 700.89, "Indonesia": 724.09,
    "Iran": 574.76, "Iraq": 730.43, "Ireland": 301.17,
    "Israel": 526.59, "Italy": 337.19, "Jamaica": 610.84,
    "Japan": 473.72, "Jordan": 550.08, "Kazakhstan": 760.07,
    "Kenya": 79.15, "Kosovo": 751.88, "Kuwait": 666.82,
    "Kyrgyzstan": 83.96, "Laos": 271.0, "Latin America": 293.69,
    "Latvia": 143.25, "Lebanon": 680.65, "Libya": 754.9,
    "Lithuania": 118.11, "Luxembourg": 107.01, "Malawi": 79.17,
    "Malaysia": 600.36, "Malta": 395.35, "Mauritius": 625.0,
    "Mexico": 457.24, "Middle East": 608.81, "Moldova": 540.25,
    "Mongolia": 950.95, "Montenegro": 380.49, "Morocco": 679.71,
    "Mozambique": 61.45, "Myanmar": 403.64, "Namibia": 108.59,
    "Nepal": 21.27, "Netherlands": 265.31, "New Caledonia": 623.08,
    "New Zealand": 171.19, "Nicaragua": 383.5, "Nigeria": 440.82,
    "North Africa": 609.35, "North America": 366.96, "North Macedonia": 539.63,
    "Norway": 31.46, "Oceania": 478.8, "Oman": 554.14,
    "Pakistan": 415.34, "Panama": 197.04, "Papua New Guinea": 614.39,
    "Paraguay": 26.24, "Peru": 256.52, "Philippines": 576.73,
    "Poland": 649.25, "Portugal": 152.05, "Puerto Rico": 640.7,
    "Qatar": 492.25, "Romania": 229.69, "Russia": 391.03,
    "Saudi Arabia": 706.91, "Senegal": 553.57, "Serbia": 620.65,
    "Singapore": 430.97, "Slovakia": 123.17, "Slovenia": 198.68,
    "South Africa": 820.12, "South America": 258.08, "South Korea": 436.69,
    "South Sudan": 522.22, "Spain": 163.1, "Sri Lanka": 499.72,
    "Sub-Saharan Africa": 427.32, "Sudan": 205.88, "Sweden": 44.95,
    "Switzerland": 52.81, "Syria": 719.47, "Taiwan": 562.56,
    "Tajikistan": 49.43, "Tanzania": 258.45, "Thailand": 506.59,
    "Togo": 503.22, "Trinidad and Tobago": 570.88, "Tunisia": 604.54,
    "Turkey": 441.06, "Turkmenistan": 1062.59, "Uganda": 72.31,
    "Ukraine": 206.39, "United Arab Emirates": 467.51, "United Kingdom": 217.09,
    "United States of America": 383.78, "Uruguay": 96.7, "Uzbekistan": 1121.18,
    "Vanuatu": 500.0, "Venezuela (Bolivarian Republic of)": 180.25, "Viet Nam": 484.32,
    "Virgin Islands (British)": 647.06, "Virgin Islands (U.S.)": 641.79, "World": 471.59,
    "Yemen": 586.32, "Zambia": 111.0, "Zimbabwe": 298.44,
  },

  // ── Reactor parameters by scale (from process_efficiency.csv) ─────────────
  // Keys: scale in litres. Fields match process_logic.py: d (m), Np, N (s⁻¹),
  // Vmix (m³), A (m²), ka (W/m²·K), n_heat (fraction).
  reactorParams: {
    100:   { d: 0.173, Np: 0.79, N: 3.052, Vmix: 0.1,  A: 1.271,  ka: 0.56, n_heat: 0.72 },
    500:   { d: 0.296, Np: 0.79, N: 1.785, Vmix: 0.5,  A: 3.716,  ka: 0.56, n_heat: 0.74 },
    1000:  { d: 0.373, Np: 0.79, N: 1.417, Vmix: 1.0,  A: 5.899,  ka: 0.56, n_heat: 0.75 },
    5000:  { d: 0.638, Np: 0.79, N: 0.828, Vmix: 5.0,  A: 17.249, ka: 0.56, n_heat: 0.77 },
    10000: { d: 0.803, Np: 0.79, N: 0.658, Vmix: 10.0, A: 27.381, ka: 0.56, n_heat: 0.79 },
  },

  // ── Solvent filtering ─────────────────────────────────────────────────────
  solventSets: ['Full set', 'Large set', 'Medium set', 'Small set'],

  // Hazard notes shown alongside each checkbox
  hazardNotes: {
    chronicToxicity:  'CMR (H340, H350, H360) or specific target organ toxicity (H372)',
    suspectedChronic: 'Suspected CMR (H341, H351, H361) or specific target organ toxicity (H373)',
    acuteToxicity:    'Acute toxicity (H300, H310, H330, H301, H311, H331) or STOT single exposure (H370, H371)',
    envPBT:           'PBT (persistent and bioaccumulating and toxic) or vPvB',
    envToxicity:      'Chronic environmental toxicity (H410, H411) or hazardous for the ozone layer (H420/EUH059)',
  },
};
